### ISSUE TITLE
Need help lots of errors

### ISSUE THREAD

**Issue by malos777** [jasperan/whatsapp-osint#14]
Hello,
first thanks for sharing this projects. 
i have lots of errors. maybe some solution?

wa/whatsapp-osint# python3 whatsappbeacon.py --username "Blumi" --language "en"
In order to make this program to work, you will need to log-in once in WhatsApp. After that, your session will be saved until you revoke it.
Traceback (most recent call last):
  File "/home/peter/wa/whatsapp-osint/whatsappbeacon.py", line 144, in <module>
    main()
  File "/home/peter/wa/whatsapp-osint/whatsappbeacon.py", line 138, in main
    driver = whatsapp_login()
  File "/home/peter/wa/whatsapp-osint/whatsappbeacon.py", line 116, in whatsapp_login
    driver = webdriver.Chrome(options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /snap/chromium/2424/usr/lib/chromium-browser/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55f869bf3603 <unknown>
#1 0x55f8699448b6 <unknown>
#2 0x55f86996ceda <unknown>
#3 0x55f869969084 <unknown>
#4 0x55f8699aa514 <unknown>
#5 0x55f8699a9b7f <unknown>
#6 0x55f8699a11d3 <unknown>
#7 0x55f869973fb8 <unknown>
#8 0x55f8699750ee <unknown>
#9 0x55f869bba046 <unknown>
#10 0x55f869bbd3c3 <unknown>
#11 0x55f869bbdc5a <unknown>
#12 0x55f869bc5b0e <unknown>
#13 0x55f869bbe3ec <unknown>
#14 0x55f869b94ea8 <unknown>
#15 0x55f869bde318 <unknown>
#16 0x55f869bde4c3 <unknown>
#17 0x55f869bebe34 <unknown>
#18 0x7faacb159609 <unknown>

THANKS!

**Comment by BerkeGokturk71** [comment]
I think your script running , you dont close chrome window and  
you are trying to run the script again.Close chrome window and try again

**Comment by BerkeGokturk71** [comment]
Chrome not support current chrome driver.I will pull request for that
