### ISSUE TITLE
 python3 whatsappbeacon.py --username Ese --language "en"

### ISSUE THREAD

**Issue by cyberfam** [jasperan/whatsapp-osint#28]
python3 whatsappbeacon.py --username Ese --language "en"
In order to make this program to work, you will need to log-in once in WhatsApp. After that, your session will be saved until you revoke it.
The version of chrome cannot be detected. Trying with latest driver version
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.4) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "whatsappbeacon.py", line 247, in <module>
    main()
  File "whatsappbeacon.py", line 240, in main
    driver = whatsapp_login()
  File "whatsappbeacon.py", line 197, in whatsapp_login
    driver = webdriver.Chrome(options=options)
  File "/home/cyberfam/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 49, in __init__
    super().__init__(
  File "/home/cyberfam/.local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 54, in __init__
    super().__init__(
  File "/home/cyberfam/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/home/cyberfam/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/cyberfam/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/cyberfam/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
#0 0x55b2c0c504e3 <unknown>
#1 0x55b2c097fc76 <unknown>
#2 0x55b2c09a6757 <unknown>
#3 0x55b2c09a5029 <unknown>
#4 0x55b2c09e3ccc <unknown>
#5 0x55b2c09e347f <unknown>
#6 0x55b2c09dade3 <unknown>
#7 0x55b2c09b02dd <unknown>
#8 0x55b2c09b134e <unknown>
#9 0x55b2c0c103e4 <unknown>
#10 0x55b2c0c143d7 <unknown>
#11 0x55b2c0c1eb20 <unknown>
#12 0x55b2c0c15023 <unknown>
#13 0x55b2c0be31aa <unknown>
#14 0x55b2c0c396b8 <unknown>
#15 0x55b2c0c39847 <unknown>
#16 0x55b2c0c49243 <unknown>
#17 0x7fa5553e3609 start_thread

**Comment by jasperan** [comment]
Hello @cyberfam, it's not locating your chromedriver binary. Make sure you put it somewhere where your PATH variable recognizes it.

Follow this tutorial if you're in Windows: [YouTube Tutorial](https://www.youtube.com/watch?v=VO64s7TYbOk)

**Comment by jasperan** [comment]
If you're in Linux, add the location of your chromedriver binary to your PATH variable in your ~/.bashrc file (or whichever way you want)
